adjective1 = input("Enter an adjetive (description):")
noun = input("Enter a noun (Person, Place, thing):")
adjective2 = input("Enter an adjective  (description):")
verb = input("Enter a verb ending with 'ing': ")
adjective3 = input("Enter an adjective (description):")
print(f"Today i went to the {adjective1} Space.")
print(f"In a place , I saw a {noun}")
print(f"{noun} was {adjective2} and {verb}")
print(f"I was {adjective3}!")
